name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Create env file
        run: |
          echo "FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }}" >> .env
          echo "FIREBASE_AUTH_DOMAIN=${{ secrets.FIREBASE_AUTH_DOMAIN }}" >> .env
          echo "FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}" >> .env
          echo "FIREBASE_DATABASE_URL=${{ secrets.FIREBASE_DATABASE_URL }}" >> .env
          echo "FIREBASE_STORAGE_BUCKET=${{ secrets.FIREBASE_STORAGE_BUCKET }}" >> .env
          echo "FIREBASE_MESSAGING_SENDER_ID=${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}" >> .env
          echo "FIREBASE_APP_ID=${{ secrets.FIREBASE_APP_ID }}" >> .env
          echo "JOSHUA_PROJECT_API_KEY=${{ secrets.JOSHUA_PROJECT_API_KEY }}" >> .env

      - name: Install Dependencies
        run: |
          npm init -y
          npm install dotenv

      - name: Process Environment Variables
        run: |
          node -e "
            const fs = require('fs');
            require('dotenv').config();
            
            const content = fs.readFileSync('src/js/firebaseConfig.js', 'utf8');
            const updatedContent = content
              .replace(/process\.env\.FIREBASE_API_KEY/g, '\"${{ secrets.FIREBASE_API_KEY }}\"')
              .replace(/process\.env\.FIREBASE_AUTH_DOMAIN/g, '\"${{ secrets.FIREBASE_AUTH_DOMAIN }}\"')
              .replace(/process\.env\.FIREBASE_PROJECT_ID/g, '\"${{ secrets.FIREBASE_PROJECT_ID }}\"')
              .replace(/process\.env\.FIREBASE_DATABASE_URL/g, '\"${{ secrets.FIREBASE_DATABASE_URL }}\"')
              .replace(/process\.env\.FIREBASE_STORAGE_BUCKET/g, '\"${{ secrets.FIREBASE_STORAGE_BUCKET }}\"')
              .replace(/process\.env\.FIREBASE_MESSAGING_SENDER_ID/g, '\"${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}\"')
              .replace(/process\.env\.FIREBASE_APP_ID/g, '\"${{ secrets.FIREBASE_APP_ID }}\"')
              .replace(/process\.env\.JOSHUA_PROJECT_API_KEY/g, '\"${{ secrets.JOSHUA_PROJECT_API_KEY }}\"');
            
            fs.writeFileSync('src/js/firebaseConfig.js', updatedContent);
          "

      - name: Prepare for deployment
        run: |
          # Create deployment directory
          mkdir -p public
          
          # Copy HTML files to root
          cp src/html/*.html public/
          
          # Create asset directories
          mkdir -p public/css public/js public/data public/images
          
          # Copy assets
          cp -r src/css/* public/css/
          cp -r src/js/* public/js/
          cp -r data/* public/data/
          cp -r images/* public/images/
          
          # Move index.html to root
          cp public/index.html public/index.html
          
          # Create .nojekyll file to bypass Jekyll processing
          touch public/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public
          branch: gh-pages
          clean: true
